services:
  - type: web
    name: restaurant-api
    env: node
    plan: free
    rootDir: .
    buildCommand: npm ci
    startCommand: npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: MONGODB_URI
        sync: false
      - key: MONGO_DBNAME
        sync: false
